### ISSUE TITLE
ERROR: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by adminrezo** [hacksalot/HackMyResume#115]
Hi,

Thanks for your work.

I got this error while building or analyzing my resume.
When I validate, it seems Ok : 
```
hackmyresume VALIDATE resume.json -d

*** HackMyResume v1.5.2 ***
Reading resume: resume.json
Validating resume.json against FRESH schema: VALID!
```

I used both HackMyResume and FluentCV and none work : 

```
hackmyresume BUILD resume.json TO out/resume.all -d

*** HackMyResume v1.5.2 ***
Reading resume: resume.json
ERROR: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Object.module.exports.toFRESH (/usr/local/lib/node_modules/hackmyresume/src/core/convert.js:35:25)
    at Object.module.exports.loadOne (/usr/local/lib/node_modules/hackmyresume/src/core/resume-factory.js:69:64)
    at /usr/local/lib/node_modules/hackmyresume/src/core/resume-factory.js:38:21
    at Array.map (native)
    at Object.module.exports.load (/usr/local/lib/node_modules/hackmyresume/src/core/resume-factory.js:37:22)
    at build (/usr/local/lib/node_modules/hackmyresume/src/verbs/build.js:58:32)
    at Command.execVerb (/usr/local/lib/node_modules/hackmyresume/src/index.js:177:28)
    at Command.<anonymous> (/usr/local/lib/node_modules/hackmyresume/src/index.js:110:16)
    at Command.listener (/usr/local/lib/node_modules/hackmyresume/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
```

Is something wrong in my Json resume or is it a bug ?

Thanks in advance for your help.

**Comment by hacksalot** [comment]
Hi @adminrezo are you able to run this?

```bash
hackmyresume new rez.json
hackmyresume build rez.json
```

Let me know. Thanks~

**Comment by adminrezo** [comment]
Yes, those commands work.
I think my Json file is not proper but I validated it with hmr and with an online Json validator, I don't find anything wrong.

**Comment by hacksalot** [comment]
Thanks @adminrezo. Please retry in [v1.6.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.6.0) if you're still experiencing this issue.
