### ISSUE TITLE
hackmyresume BUILD from JSON Resume themes broken

### ISSUE THREAD

**Issue by j0rdsta** [hacksalot/HackMyResume#128]
Hey there,

I've been using JSON Resume for the past few weeks, and have since discovered your wonderful project (better in multiple ways I might add, great job!). I've attempted to move across my JSON resume schema and the theme I was developing for it, but I've had some issues in the past release or two with running the `hackmyresume BUILD` command. This seems to happen for any JSON resume theme: I've just tested [one featured on the jsonresume.org website called 'flat'](https://github.com/erming/jsonresume-theme-flat) with no luck either.

Here's the command line output when running this `hackmyresume build resume-fresh.json to out/resume.all -t themes/jsonresume-theme-flat -d` command:

````bash
*** HackMyResume v1.7.3 ***
The -d or --debug switch was specified. DEBUG mode engaged.

  Platform:              darwin
  Node.js:               v5.5.0
  HackMyResume:          v1.7.3
  FRESCA:                ~0.6.0

OPTIONS:

  theme                  themes/jsonresume-theme-flat
  prettify               true
  css                    undefined
  pdf                    undefined
  sort                   true
  tips                   undefined
  debug                  true

Invoking BUILD command.
Reading FRESH resume: resume-fresh.json
Verifying THEMES/JSONRESUME-THEME-FLAT theme.
Applying THEMES/JSONRESUME-THEME-FLAT theme (? formats)
TypeError: (intermediate value).open is not a function
    at loadTheme (/Users/jordsta/.node/lib/node_modules/hackmyresume/dist/verbs/build.js:411:79)
    at Class.build (/Users/jordsta/.node/lib/node_modules/hackmyresume/dist/verbs/build.js:132:32)
    at Class.module.exports.Verb.extend.invoke (/Users/jordsta/.node/lib/node_modules/hackmyresume/dist/verbs/build.js:86:19)
    at Command.execute (/Users/jordsta/.node/lib/node_modules/hackmyresume/dist/cli/main.js:211:14)
    at Command.<anonymous> (/Users/jordsta/.node/lib/node_modules/hackmyresume/dist/cli/main.js:82:15)
    at Command.listener (/Users/jordsta/.node/lib/node_modules/hackmyresume/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/Users/jordsta/.node/lib/node_modules/hackmyresume/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/jordsta/.node/lib/node_modules/hackmyresume/node_modules/commander/index.js:458:21)
Exiting with error code 22
````

`themes/jsonresume-theme-flat` is a directory inside the working directory. I've also confirmed that `resume-fresh.json` is in valid FRESH/FRESCA format by using the `VALIDATE` command:

````bash
*** HackMyResume v1.7.3 ***
Validating resume-fresh.json against the fresh schema: VALID!
````

The `BUILD` command was most certainly working 2-4 releases ago when I originally installed the package.

Can anyone assist with fixing this bug? I'd help, but I'm lacking some Node know-how.

Cheers,
Jordan

**Comment by hacksalot** [comment]
Hi @j0rdsta thanks for the report and the encouraging words! This regression is fixed for the next version, will update in an hour or two.

**Comment by j0rdsta** [comment]
Legend! Thanks a bunch for the quick fix @hacksalot!
