### ISSUE TITLE
Invoking Build fails due to TypError

### ISSUE THREAD

**Issue by seiflotfy** [hacksalot/HackMyResume#129]
I get the following when trying to BUILD a resume
```bash

*** HackMyResume v1.7.3 ***
The -d or --debug switch was specified. DEBUG mode engaged.

  Platform:              darwin
  Node.js:               v5.5.0
  HackMyResume:          v1.7.3
  FRESCA:                ~0.6.0

OPTIONS:

  theme                  positive
  prettify               true
  css                    undefined
  pdf                    undefined
  sort                   true
  tips                   undefined
  debug                  true

Invoking BUILD command.
Reading FRESH resume: seiflotfy.json
Verifying POSITIVE theme.
Applying POSITIVE theme (8 formats)
[TypeError: w.safe.end.unix is not a function]
TypeError: w.safe.end.unix is not a function
    at /usr/local/lib/node_modules/hackmyresume/dist/core/fresh-resume.js:401:31
    at /usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:313:20
    at Function._.each._.forEach (/usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:153:9)
    at Function._.max (/usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:312:9)
    at FreshResume.duration (/usr/local/lib/node_modules/hackmyresume/dist/core/fresh-resume.js:399:24)
    at FreshResume.parseJSON (/usr/local/lib/node_modules/hackmyresume/dist/core/fresh-resume.js:107:26)
    at Class.build (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:194:38)
    at Class.module.exports.Verb.extend.invoke (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:86:19)
    at Command.execute (/usr/local/lib/node_modules/hackmyresume/dist/cli/main.js:211:14)
    at Command.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/cli/main.js:82:15)
```

I am using node version 5.5.0

**Comment by hacksalot** [comment]
Thanks for the report @seiflotfy -- looks like HMR isn't interpreting the missing end date correctly (missing end date should be interpreted as "current" or "present" etc.). Will roll this into today's build.

**Comment by hacksalot** [comment]
Out of curiosity are you using `present` or `current` or some other value for the end date in that spot? Or omitting it entirely?
