### ISSUE TITLE
Adjust datetime semantics

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#130]
Currently you can indicate that a job or position is "current" in HMR and FRESH by

- Omitting the `end` date.
- Setting the `end` date to `'present'`, `'current'`, or `'now'`.
- Setting the `end` date to `null`, `undefined`, an empty string `""`, or a string containing only white space (`"    "`)
- Setting the `current` flag to `true`.

This works for most purposes, but there's no way under this scheme to indicate when a date is simply **unspecified** or intentionally omitted from the resume, because all of the values that would normally indicate that (`null`, empty string, etc.) have been soaked up by the semantics around current / present dates.

This change will introduce a slight tweak to how missing or unspecified datetimes are treated.

1. If the `end` field is present *but has been set to a value like `null`, `undefined`, or the empty string `""`*, HMR will interpret that not as "currently employed" but as "date purposefully omitted by the user".

2. HMR will not compute durations or otherwise try to reason about jobs/projects/etc. that have unspecified dates. With "current", HMR can infer that the job duration is currently at `now - start`. Not so with an unspecified date.

**Comment by EpicNuts** [comment]
Hey, is this related to the 'Moment' issue? 

Trying to build anything from a JSON Resume results in:

```
$ hackmyresume build benstest.json to benstest.html

*** HackMyResume v1.8.0 ***
Reading JRS resume: benstest.json
Converting benstest.json to FRESH format.
Applying MODERN theme (8 formats)
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to ttps://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:850:105)
    at configFromString (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:970:32)
    at configFromInput (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:1473:13)
    at prepareConfig (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:1456:13)
    at createFromConfig (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:1423:44)
    at createLocalOrUTC (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:1505:16)
    at local__createLocal (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:1509:16)
    at utils_hooks__hooks (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\moment\moment.js:16:29)
    at FluentDate.fmt (c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\dist\core\fluent-date.js:83:14)
    at c:\Users\Gapped\AppData\Roaming\npm\node_modules\hackmyresume\dist\core\fresh-esume.js:490:29
```

**Comment by hacksalot** [comment]
Moment deprecated certain date-creation patterns a while back which leads to the warning/error shown. HMR can and should avoid this in client-side code so I'm inclined to call this a bug on our side. +1 and thanks for the report.
