### ISSUE TITLE
Issues Building using Flat theme

### ISSUE THREAD

**Issue by jyounus** [hacksalot/HackMyResume#140]
Hey there,

First of all thanks for making this awesome project!

I've created a quick sample resume file and want to build it using the Flat theme. However I get the following errors in the console:

```

jayys-MacBook-Pro:MyResume jayy$ hackmyresume BUILD resume-jrs.json TO out/resume.all -t node_modules/jsonresume-theme-flat/ -d

*** HackMyResume v1.7.5 ***
The -d or --debug switch was specified. DEBUG mode engaged.

  Platform:              darwin
  Node.js:               v0.12.7
  HackMyResume:          v1.7.5
  FRESCA:                ~0.6.0

OPTIONS:

  theme                  node_modules/jsonresume-theme-flat/
  prettify               true
  css                    undefined
  pdf                    undefined
  sort                   true
  tips                   undefined
  debug                  true

Invoking BUILD command.
Reading JRS resume: resume-jrs.json
Verifying NODE_MODULES/JSONRESUME-THEME-FLAT/ theme.
Applying JSONRESUME-THEME-FLAT theme (5 formats)
Generating HTML resume: out/resume.html
Error: EISDIR, illegal operation on a directory '/Users/jayy/Documents/NodeJS/MyResume/out'
Error: EISDIR, illegal operation on a directory '/Users/jayy/Documents/NodeJS/MyResume/out'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at HtmlGenerator.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/generators/template-generator.js:136:14)
    at Array.forEach (native)
    at HtmlGenerator.module.exports.TemplateGenerator.generate (/usr/local/lib/node_modules/hackmyresume/dist/generators/template-generator.js:115:21)
    at BuildVerb._single (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:288:29)
    at BuildVerb.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:208:25)
    at /usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:73:21
    at Function._.each._.forEach (/usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:153:9)
Generating PDF  resume: out/resume.pdf
Error: EISDIR, illegal operation on a directory '/Users/jayy/Documents/NodeJS/MyResume/out'
Error: EISDIR, illegal operation on a directory '/Users/jayy/Documents/NodeJS/MyResume/out'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at HtmlPdfCLIGenerator.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/generators/template-generator.js:136:14)
    at Array.forEach (native)
    at HtmlPdfCLIGenerator.module.exports.TemplateGenerator.generate (/usr/local/lib/node_modules/hackmyresume/dist/generators/template-generator.js:115:21)
    at BuildVerb._single (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:288:29)
    at BuildVerb.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:208:25)
    at /usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:73:21
    at Function._.each._.forEach (/usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:153:9)
Generating JSON resume: out/resume.json
Generating YML  resume: out/resume.yml
Generating PNG  resume: out/resume.png
Error: TypeError: Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at HtmlPngGenerator.module.exports.HtmlPngGenerator.generate (/usr/local/lib/node_modules/hackmyresume/dist/generators/html-png-generator.js:44:44)
    at BuildVerb._single (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:295:29)
    at BuildVerb.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:208:25)
    at /usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:73:21
    at Function._.each._.forEach (/usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:153:9)
    at BuildVerb._build [as workhorse] (/usr/local/lib/node_modules/hackmyresume/dist/verbs/build.js:203:7)
    at /usr/local/lib/node_modules/hackmyresume/dist/verbs/verb.js:48:24
    at BuildVerb.module.exports.Verb.invoke (/usr/local/lib/node_modules/hackmyresume/dist/verbs/verb.js:45:29)
    at Command.execute (/usr/local/lib/node_modules/hackmyresume/dist/cli/main.js:220:21)
    at Command.<anonymous> (/usr/local/lib/node_modules/hackmyresume/dist/cli/main.js:90:15)
Exiting with status code [object Object].

```

Any ideas what the issue is? I installed from the dev branch via npm. It only generates a .json and .yml file, all the other formats are not created inside the /out/ folder.

**Comment by hacksalot** [comment]
Thanks @jyounus! -- every once in a while `dev` gets into a messy state, should be resolved shortly.

**Comment by hacksalot** [comment]
This is now resolved locally and on Travis, and verified against the Flat theme. Let me know if you still experience this issue on the latest `dev` or in the next official release and I'll re-open. Thanks~

**Comment by jyounus** [comment]
Installed the latest from dev, it now works! Thanks! :D

Just a quick question, it didn't generate my resume in a Word format, is that different/dependant on the theme that I use? In other words, am I right in assuming that some themes only support certain output formats? Without specifying a custom theme (and just using the default "modern" one), it does generate a Word format (which I can't open on my Mac using Pages).

**Comment by hacksalot** [comment]
Cool, glad to hear it!

The Word output format is dependent on (provided by) the theme. There are two kinds of themes:

- FRESH themes
- JSON Resume themes.

Only FRESH themes support the MS Word output format currently -- officially -- but that doesn't mean a JSON Resume theme couldn't be translated to MS Word. HackMyResume isn't affiliated with JSON Resume, so this isn't really on our menu, but to the extent JSON Resume's own tools start supporting an MS Word rendering path, we'll follow suit.

Back on the FRESH side, there's already explicit support for MS Word, but the MS Word formats need some more polish before the themes project leaves beta. If you're working with the MS Word format, look for a big round of cosmetic updates later this week.

The Pages issue is a known issue caused by the fact that most of the Word formats were originally built on Windows, since Word really originates there, and at the time the theme templating system wasn't robust enough to adjust OS-specific cruft (for example: line endings, OS-specific font descriptions, and the like). This should also be resolved in the next week or so.

**Comment by jyounus** [comment]
Appreciate the detailed answer! 
Not really a big deal for me right now, but good to know it's something that will eventually be supported. :)
