### ISSUE TITLE
Tests: jane-q-fullstacker work duration expected 8 to equal 7

### ISSUE THREAD

**Issue by peternowee** [hacksalot/HackMyResume#181]
Three automated tests of test-fresh-sheet and test-jrs-sheet for jane-q-fullstacker fail, expecting a work duration of 7 years, but seeing an actual value of 8:

      1) jane-q-fullstacker (FRESH) should have a work duration of 7 years:
    
          AssertionError: expected 8 to equal 7
          + expected - actual
    
          -8
          +7
          
        at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:487:12)
        at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
        at Context.<anonymous> (test/scripts/test-fresh-sheet.js:45:41)
      
    
      2) jane-q-fullstacker B (FRESH) should have a work duration of 7 years:
    
          AssertionError: expected 8 to equal 7
          + expected - actual
    
          -8
          +7
          
        at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:487:12)
        at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
        at Context.<anonymous> (test/scripts/test-fresh-sheet.js:45:41)
      
    
      3) jane-q-fullstacker (JRS) should have a work duration of 7 years:
    
          AssertionError: expected 8 to equal 7
          + expected - actual
    
          -8
          +7
          
        at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:487:12)
        at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
        at Context.<anonymous> (test/scripts/test-jrs-sheet.js:47:46)

These failures occur with both the current HEAD of branch master (1.8.0) and the current HEAD of branch dev (1.9.0) and in both Node.js 0.10.29 on Debian Jessie and Node.js 4.6.1 on Debian unstable.

**Comment by hacksalot** [comment]
Thanks for the report. I've updated the durations as a quick fix. Need to allow for open-ended durations (MM/DD/YYYY to present) where it will return 6 this year, 7 next, etc.
