### ISSUE TITLE
Moment.js Deprecation warning for date

### ISSUE THREAD

**Issue by prajankya** [hacksalot/HackMyResume#190]
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

with the latest update of moment

**Comment by prajankya** [comment]
at  FluentDate.fmt /hackmyresume/dist/core/fluent-date.js:83:14
at /hackmyresume/dist/core/fresh-resume.js:490:29
