### ISSUE TITLE
Unable to create a custom theme

### ISSUE THREAD

**Issue by adenta** [hacksalot/HackMyResume#210]
Locally I am trying to modify the compact theme. I cloned the repo, and am using the command: 
` hackmyresume build #{input_file_path} TO #{output_file_path} -t lib/assets/fresh-theme-compact -d"`

My stacktracke looks like: 

*** HackMyResume v1.9.0-beta ***
The -d or --debug switch was specified. DEBUG mode engaged.

  Platform:              darwin
  Node.js:               v8.6.0
  HackMyResume:          v1.9.0-beta
  FRESCA:                undefined

OPTIONS:

  theme                  lib/assets/fresh-theme-compact
  prettify               true
  css                    undefined
  pdf                    undefined
  sort                   true
  tips                   undefined
  private                undefined
  escape                 true
  debug                  true

Invoking BUILD command.
Reading FRESH resume: /Users/adenta/projects/handshake-office/tmp/resume/53490199057853909535398187846744558961_resume.json
Verifying LIB/ASSETS/FRESH-THEME-COMPACT theme.
Applying FRESH-THEME-COMPACT theme (8 formats)
Generating HTML resume: tmp/resume/53490199057853909535398187846744558961_resume.html
An error occurred during template invocation.
   TypeError: Cannot read property 'operator' of undefined
TypeError: Cannot read property 'operator' of undefined
    at Object.compare (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/dist/helpers/generic-helpers.js:505:30)
    at Object.<anonymous> (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/dist/helpers/handlebars-helpers.js:40:23)
    at executeBound (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/underscore/underscore.js:701:67)
    at Object.bound (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/underscore/underscore.js:733:14)
    at eval (eval at createFunctionContext (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:79)
    at prog (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:31)
    at Object.prog [as fn] (/Users/adenta/projects/handshake-office/node_modules/hackmyresume/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
Exiting with status code [object Object].
  deterministically generates the same output file (FAILED - 1)

Happy to provide any additional information to get this working

**Comment by adenta** [comment]
`npm install` solved my problem. I feel like we could probably have hackmyresume do this for people in the future.

```
if <npm directory doesn't exist>
  run 'npm install'
```
