### ISSUE TITLE
Multiple Sources -- ERROR: extend is not defined

### ISSUE THREAD

**Issue by aaboyd** [hacksalot/HackMyResume#68]
When using multiple sources on Windows 10 I receive the following error.

```
*** HackMyResume v1.2.2 ***
Reading SOURCE resume: .\basics.json
Reading SOURCE resume: .\education.json
ERROR: extend is not defined
ReferenceError: extend is not defined
    at C:\Users\Alex\AppData\Roaming\npm\node_modules\hackmyresume\src\verbs\generate.js:48:14
    at iterator (C:\Users\Alex\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\underscore\underscore.js:184:16)
    at Function.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_modules\hackmyresume\node_modules\underscore\underscore.js:199:14)
    at generate (C:\Users\Alex\AppData\Roaming\npm\node_modules\hackmyresume\src\verbs\generate.js:45:13)
    at main (C:\Users\Alex\AppData\Roaming\npm\node_modules\hackmyresume\src\index.js:75:22)
    at Object.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_modules\hackmyresume\src\index.js:22:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by zhuangya** [comment]
hmm nice catch , it is a bug. i'm commit a PR for this :+1:
