### ISSUE TITLE
Network error: wkhtmltopdf

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#74]
`wkhtmltopdf` can return this error when there's no internet access:

```bash
events.js:85
      throw er; // Unhandled 'error' event

Error: Exit with code 1 due to network error: HostNotFoundError
    at Socket.<anonymous> (/dev/hmr/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
```

Respond to this gracefully and figure out why wkhtmltopdf is dialing home.

**Comment by troyleak** [comment]
I'm having the same error on my system, internet access is fine. 

```$ hackmyresume BUILD resume.json TO out/resume.all

*** HackMyResume v1.3.1 ***
Applying MODERN theme (5 formats)
Reading resume: resume.json
Generating DOC resume: out/resume.doc
Generating HTML resume: out/resume.html
Generating MD resume: out/resume.md
Generating PDF resume: out/resume.pdf
Generating TXT resume: out/resume.txt
Generating JSON resume: out/resume.json
Generating YML resume: out/resume.yml
Generating PNG resume: out/resume.png
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: /bin/sh: wkhtmltopdf: command not found
    at Socket.<anonymous> (/usr/local/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by jarz** [comment]
The [wkhtmltopdf package](https://github.com/devongovett/node-wkhtmltopdf) hasn't seen code updates in ~2 years. Using [wkhtmltopdf-installer](https://www.npmjs.com/package/wkhtmltopdf-installer) might be better to use since it automagically grabs the binary.

**Comment by jarz** [comment]
Looking at wkhtmltopdf's [issues](https://github.com/wkhtmltopdf/wkhtmltopdf/search?q=HostNotFoundError&type=Issues&utf8=%E2%9C%93), this appears to be an upstream issue they're still tracking down.

**Comment by hacksalot** [comment]
@jarz interesting. We will probably remove the wkhtmltopdf API dependency and start using it (and Phantom) via command line. Still handled by HMR, but going through the CLI rather than the API.

Merging this with #58 please update there. Thanks!
