### ISSUE TITLE
Errors When Command Not Found

### ISSUE THREAD

**Issue by jjanusch** [hacksalot/HackMyResume#83]
I tried running the standard `--help` command and got the following:

```
*** HackMyResume v1.3.1 ***
ERROR: Cannot read property 'warn' of undefined
TypeError: Cannot read property 'warn' of undefined
    at main (/usr/local/lib/node_modules/hackmyresume/src/index.js:59:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/hackmyresume/src/index.js:27:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I realized after the fact that I should run `hackmyresume help`, but I don't think that should throw a Node error. Ideally, it should output something to the effect of `--help is an invalid command. Did you mean 'help'?`.

**Comment by hacksalot** [comment]
+1

**Comment by jjanusch** [comment]
Generally, I see `-h` and  `--help`. I've never seen `/?`, but if it's out there, I don't see why it shouldn't be supported.

Additionally, `--version` and `-v` should probably also be supported. While it does say `*** HackMyResume v1.3.1 ***` at the top of all output, that is generally expected to be a valid command that outputs the version number.

```bash
$ git --version
git version 2.3.3
$ vagrant --version
Vagrant 1.8.1
$ npm --version
2.5.1
$ gulp --version
[15:10:10] CLI version 3.9.0
[15:10:10] Local version 3.9.0
$ hackmyresume --version

*** HackMyResume v1.3.1 ***
ERROR: Cannot read property 'warn' of undefined
TypeError: Cannot read property 'warn' of undefined
    at main (/usr/local/lib/node_modules/hackmyresume/src/index.js:59:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/hackmyresume/src/index.js:27:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by hacksalot** [comment]
Agreed. `--help` is already partially implemented on dev, `-v` and `--version` forthcoming.

**Comment by zhuangya** [comment]
@hacksalot take a look at [commander.js](https://www.npmjs.com/package/commander) maybe?

**Comment by hacksalot** [comment]
@zhuangya Yeah, I think it's time. With the new set of HMR verbs (`analyze`, `merge`, etc.) and options (including local `.hackmyrc`) we need a bit more consistency and structure around command invocations. Side note, Colors has been replaced with Chalk so in the next version you can do `--no-color`.

**Comment by hacksalot** [comment]
Commander.js is in (and `--help` with it) but I've had to monkey patch things a bit.
