### ISSUE TITLE
Private fields

### ISSUE THREAD

**Issue by robertmain** [hacksalot/HackMyResume#88]
It would be nice to be able to mark fields (such as address) as private and then use a `--private` flag to omit those fields when generating a CV. This seems particularly relevant when using hackmycv to generate an online resume where I might not really want to publish my address...

**Comment by jarz** [comment]
Check out [merging resumes](https://github.com/hacksalot/HackMyResume#merging-resumes). That's what I'd planned to do.

**Comment by robertmain** [comment]
Oh I see...that's interesting - so I could have a base one without my address and then just provide that as and when in a separate one?

**Comment by hacksalot** [comment]
Several options here:

- Today: Use resume merging.
- Soon: A privatize filter (similar to what @robertmain is suggesting)
- Soon: An `anonymize` command or option to replace personally identifiable information with safe equivalents / resume ipsem.

**Comment by robertmain** [comment]
It's worth clarifying that I was suggesting that it would be nice to be able to add private = true to **any** field to remove it from the resume if run with --private.

**Comment by SignpostMarv** [comment]
@robertmain One assumes that if a field is marked as private it should be private by default, i.e. use a --include-private flag to show them?

**Comment by hacksalot** [comment]
@robertmain Yeah I think that makes sense. In addition to that, a filter:

```javascript
// .hackmyrc
{
  exclude: [
    'info.address', 'info.phone', 'info.email', 
    'employment[3].employer'. 'employment[*].employer', 'etc'
  ]
}
```

It's hard to attach `.private` property to a naked string field in JSON anyway, so we offer the declarative approach too.

**Comment by robertmain** [comment]
yeah, that would be cool

**Comment by robertmain** [comment]
@hacksalot I tried to use resume merging and this is what happened:


	$ hackmyresume BUILD resume.json private.json TO out.all

	*** HackMyResume v1.3.1 ***
	Applying MODERN theme (5 formats)
	Reading resume: resume.json
	Reading resume: private.json
	ERROR: Cannot read property 'imp' of undefined
	TypeError: Cannot read property 'imp' of undefined
	    at /home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/src/verbs/generate.js:67:30
	    at iterator (/home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:184:16)
	    at Function.<anonymous> (/home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:199:14)
	    at build (/home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/src/verbs/generate.js:65:20)
	    at main (/home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/src/index.js:79:42)
	    at Object.<anonymous> (/home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/src/index.js:27:3)
	    at Module._compile (module.js:425:26)
	    at Object.Module._extensions..js (module.js:432:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:311:12)

**Comment by hacksalot** [comment]
@robertmain If you install latest with

`npm install hacksalot/hackmyresume#dev -g` (you may need to `npm uninstall hackmyresume -g` first)

does this still occur?

**Comment by robertmain** [comment]
Unfortunately it does.

**Comment by hacksalot** [comment]
Ah, okay. Thanks for the report -- related issue to [    ]. should be fixed shortly. Will update.

**Comment by robertmain** [comment]
No probs :) Also you forgot to include the issue number :)

**Comment by hacksalot** [comment]
If anybody is still experiencing this issue in the latest versions (v1.4.x) please update here. Thanks.

**Comment by robertmain** [comment]
I'm having a slightly different issue now where the data from the specific resume is just missing from the files output

**Comment by hacksalot** [comment]
I'll add more tests around merging and hopefully resolve this finally for 1.5.1.

For now you can use `--no-tips` to disable theme warnings/messages. In future versions theme messages will display only the first couple times, or when the `--tips` or `--debug` flag is set.

**Comment by hacksalot** [comment]
Re: the original feature request, HMR 1.6.0 supports an `.ignore` flag (on any section or property) that effectively removes the property from the resume prior to processing. Eg:

```js
"education": {
  "history": [
    {
      "name": "foo",
      "ignore": true
      /* etc */
    }
  ]
}
```

Next up: `.private` and `--private`.

**Comment by robertmain** [comment]
What is the `name` field for?

**Comment by hacksalot** [comment]
Er, `employer`.

**Comment by ryneeverett** [comment]
> It's worth clarifying that I was suggesting that it would be nice to be able to add private = true to any field to remove it from the resume if run with --private.

It seems like this use case (and many others) could be served by a more powerful tagging/labelling/flavouring system in which fields, or even entire sections, could be selected or deselected for a given build based on an arbitrary identifier. For example, you could label a field "not private" and build with "--flavor private" and I might label some of my sections "orange" and build with "--flavor orange" to exclude non-orange sections.
