### ISSUE TITLE
Failed to generate PDF for JSON Resume theme

### ISSUE THREAD

**Issue by umpirsky** [hacksalot/HackMyResume#93]
With version 1.4.2 on Ubuntu 15.10:

```
$ node_modules/.bin/hackmyresume BUILD resume.json TO resume.pdf -t node_modules/jsonresume-theme-slick

*** HackMyResume v1.4.2 ***
Reading resume: resume.json
Applying JSONRESUME-THEME-SLICK theme (1 format)
ERROR: Cannot read property 'outFormat' of undefined
TypeError: Cannot read property 'outFormat' of undefined
    at single (resume/node_modules/hackmyresume/src/verbs/generate.js:151:31)
    at resume/node_modules/hackmyresume/src/verbs/generate.js:104:17
    at Array.forEach (native)
    at build (resume/node_modules/hackmyresume/src/verbs/generate.js:103:13)
    at Command.execVerb (resume/node_modules/hackmyresume/src/index.js:175:28)
    at Command.<anonymous> (resume/node_modules/hackmyresume/src/index.js:109:16)
    at Command.listener (resume/node_modules/hackmyresume/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (resume/node_modules/hackmyresume/node_modules/commander/index.js:615:12)
    at Command.parse (resume/node_modules/hackmyresume/node_modules/commander/index.js:458:21)
```

Html works:

```
$ node_modules/.bin/hackmyresume BUILD resume.json TO resume.html -t node_modules/jsonresume-theme-slick

*** HackMyResume v1.4.2 ***
Reading resume: resume.json
Applying JSONRESUME-THEME-SLICK theme (1 format)
Generating HTML resume: resume.html
The JSONRESUME-THEME-SLICK theme says: "For 
best results view JSON Resume themes over a local or remote 
HTTP connection. For example:

    http-server <resume-folder>

For more information, see the README."
```

**Comment by hacksalot** [comment]
@umpirsky Thanks for the report -- this got pushed to v1.5 since we have some lower level PDF issues to work through first. In progress now.

**Comment by hacksalot** [comment]
Should be out today. See also #96.

**Comment by hacksalot** [comment]
Fixed in [1.5.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.5.0). If you still have issues, leave a comment and I'll re-open and issue a hotfix. Thanks!

**Comment by umpirsky** [comment]
@hacksalot Thanks!

Now I have another error:

```
node_modules/.bin/hackmyresume BUILD resume.json TO resume.pdf -t node_modules/jsonresume-theme-slick

*** HackMyResume v1.5.0 ***
Reading resume: resume.json
Applying JSONRESUME-THEME-SLICK theme (2 formats)
Generating PDF  resume: resume.pdf
ERROR: [object Object]
The JSONRESUME-THEME-SLICK theme says: "For 
best results view JSON Resume themes over a local or remote 
HTTP connection. For example:

    http-server <resume-folder>

For more information, see the README."
```

**Comment by hacksalot** [comment]
Interesting, let me test with SLICK. Will have to patch a few things in 5.1 anyway.

**Comment by umpirsky** [comment]
@hacksalot Not slick specific:

```
$ node_modules/.bin/hackmyresume BUILD resume.json TO resume.pdf 

*** HackMyResume v1.5.0 ***
Reading resume: resume.json
Applying MODERN theme (5 formats)
Generating PDF  resume: resume.pdf
ERROR: [object Object]
The MODERN theme says: "To get colored skill 
progress bars, make sure your resume includes a `level` 
element for each skill!"
```

**Comment by mickmur** [comment]
@hacksalot just to let you know, pdf generation now fixed for me with 1.5. Fantastic work on this project!

**Comment by hacksalot** [comment]
Thanks @umpirsky I'll add it to the tests anyway. v1.5.1 also has a stack trace option you can set to force full exception info.

```bash
*** HackMyResume v1.5.0 ***
Reading resume: resume.json
Applying JSONRESUME-THEME-SLICK theme (2 formats)
Generating PDF  resume: out\rez.pdf
The JSONRESUME-THEME-SLICK theme says: "For
best results view JSON Resume themes over a local or remote
HTTP connection. For example:

    npm install http-server -g
    http-server <resume-folder>

For more information, see the README."
```

Is your resume missing any important sections or other obvious info? HMR's handling of those still isn't 100% but I've/we've at least figured out how to test around this so look for a sharp improvement soon. There will also shortly be an `anonymize` option so people can upload resume JSON for bug reports without revealing private details.

**Comment by caseycamichloe** [comment]
Stop emailing so much please

**Comment by umpirsky** [comment]
@hacksalot OK, I will wait for 1.5.1 to see the trace, maybe I am missing some sections. Thanks.

**Comment by hacksalot** [comment]
@caseycamichloe Yeah, that can be annoying. The emails are automated by GitHub (I'm on the web UI right now), but you can adjust your settings or disable notifications for the project.

**Comment by caseycamichloe** [comment]
Thank you so much
